name: Publish Package to npmjs
on:
  release:
    types: [created]
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest 
    
    permissions: 
      contents: read
      packages: write 

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@aleph-front'

      - name: Install dependencies
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" FONTAWESOME_NPM_AUTH_TOKEN
          npm ci

      - name: "Build package"
        run: npm run build

      - name: "Publish package"
        run: npm publish -- --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
